Resources:
  NotesCloudFrontDist:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
        - i-notes.kencarb.com
        Origins:
        - DomainName: i-notes.kencarb.com.s3-website-us-east-1.amazonaws.com
          Id: myPublicS3Origin
          CustomOriginConfig:
            HTTPPort: 443
            OriginProtocolPolicy: https-only
        Enabled: true
        DefaultRootObject: "index.html"
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          - OPTIONS
          - PUT
          - PATCH
          - POST
          - DELETE
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          TargetOriginId: myPublicS3Origin
          ViewerProtocolPolicy: https-only
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:028821943969:certificate/f6027d97-4efb-4e83-a338-9250ede38ccc
          MinimumProtocolVersion: TLSv1.2_2018
          SslSupportMethod: sni-only
      Tags:
      - Key: "App"
        Value: "InterviewNotes"
          
Outputs:
  CloudFrontDistribution:
    Value: !Ref NotesCloudFrontDist